AWSTemplateFormatVersion: 2010-09-09
Description: This template creates a simple stack.

Parameters:
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: name of the key pair to ssh into the instance
    Default: hanoi-key

  EC2InstanceType:
    Description: The Instance Type Chosen for EC2
    Type: String
    Default: t2.micro
  
  AmiId:
   Type: AWS::EC2::Image
   Description: The AMI ID to use for the EC2 instance.
   Default: ami-053b0d53c279acc90

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: !Ref AmiId
      InstanceType: !Ref EC2InstanceType
      KeyName: !Ref SSHKey
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'
      SecurityGroupIds:
        - !Ref WebAppSG

  WebAppSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow HTTP/HTTPS and SSH inbound and outbound traffic"
      GroupName: WebAppSG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9000
          ToPort: 9000
          CidrIp: 0.0.0.0/0

