Parameters:
  AmiId:
   Type: AWS::EC2::Image
   Description: The AMI ID to use for the EC2 instance.
   
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Description: The security group to associate with the EC2 instance.
    
  InstanceName:
    Type: String
    Description: The name to give the EC2 instance.
    
  InstanceType:
    Type: AWS::EC2::InstanceType
    Description: The InstanceType to use for the EC2 instance.
   
  IpAddress:
    Type: String
    Description: The IP address to assign to the EC2 instance.
   
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: name of the key pair to ssh into the instance
    

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          PrivateIpAddresses:
            - !Ref IpAddress
      HostName: !Ref InstanceName
      KeyName: !Ref SSHKey
      SecurityGroups:
        - !Ref SecurityGroup





